<?php
require_once './core/init.php';
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Civilizatia geto dacica Poiana - Muzeul Tecuci</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-1.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-grid.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-reboot.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-utilities.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap.compiled.css">
    <link rel="stylesheet" href="assets/scss/styles.css">
</head>

<body>
    <?php require_once 'navbar.php'; ?>
    <!-- <header class="masthead" style="background-image:url('assets/img/paleontologie.jpg');     background-attachment: fixed;
    background-position: bottom;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto position-relative">
                    <div class="site-heading">
                        <h1><strong>Paleontologie</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header> -->

    <header class="masthead" style="background-image:url('assets/img/getodacica.jpg');background-position:bottom center;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto position-relative">
                    <div class="site-heading">
                        <h1>Muzeul de Istorie&nbsp;</h1>
                        <h1>Teodor Cincu</h1>
                        <span class="subheading">
                            Civilizatia geto dacica Poiana
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- <h3 style="color: #0085a1;text-align: center;font-family: 'Lora',serif;">SCURT ISTORIC</h3> -->
    <h2 style="text-align: center;font-family: 'Poppins',sans-serif;"><br><strong>Colecții ale muzeului - Civilizatia geto dacica Poiana</strong><br><br></h2>
    <div class="container" style="text-align: center;">
        <div class="text_istoric">
            <div class="istoric_text_column istoric_content_element ">
                <div class="text_istoric">

                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Situl arheologic Piroboridava&nbsp;</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Aşezarea getică de la Poiana&nbsp;</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Informaţiile privitoare la teritoriile locuite de către geţi &icirc;n secolele IV-III a. Chr. sunt foarte puţine. V. P&acirc;rvan, &icirc;n 1926, analizează sursele literare &icirc;n Getica, iar ulterior, studiile speciale, ca şi lucrările de sinteză, nu au reuşit să schimbe interpretările lui V. P&acirc;rvan, ci doar să nuanţeze opiniile exprimate de acesta &icirc;n 1926.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Lipsa izvoarelor literare antice se datorează fie lipsei de interes manifestat faţă de această zonă de către istoricii vremii, fie faptului că principalele izvoare redactate &icirc;n secolele IV-II a. Chr. nu s-au păstrat ori fragmentele care au ajuns p&acirc;nă la noi sunt insuficiente pentru a reface total istoria acestei zone.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>La sf&acirc;rşitul secolului al V &ndash; lea şi &icirc;nceputul secolului al IV &ndash; lea a. Chr., de-a lungul marilor cursuri de apă apar noi aşezări, datorită creşterii demografice şi exploatării resurselor naturale şi materiale. Progresul concretizat prin organizarea politică este mai bine cunoscut prin informaţiile despre războaiele geţilor cu puteri superioare din punct de vedere politic şi militar.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Cercetarea sistematică a unor aşezări getice, identificate &icirc;ncă din secolul XIX, sau descoperite &icirc;n a doua jumătate a secolului XX, a adus date importante privind răsp&acirc;ndirea şi felul de viaţă al triburilor getice de pe teritoriul extracarpatic şi a contribuit la conturarea multor probleme din istoria Moldovei.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Aşezarea getică de la Poiana &ndash; cunoaşte &icirc;n vremea lui Burebista şi Decebal o mare &icirc;nflorire</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n ultimele două secole &icirc;naintea erei creştine se constată dezvoltarea unor aşezări intens locuite, denumite de geţi dava şi de greci polis. Fortificate cu valuri de păm&acirc;nt, palisade şi şanţuri, după vechea tradiţie din epoca bronzului şi prima epocă a fierului, ele vor cunoaşte &icirc;n vremea lui Burebista şi Decebal o mare &icirc;nflorire. N. Gostar admite că aceste fortificaţii naturale, pe locuri &icirc;nalte, &icirc;ntărite apoi cu ziduri şi palisade, sunt adevărate &oacute;re enteteichism&eacute;na (munţi &icirc;ntăriţi cu ziduri).</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Expresia aparţine istoricului grec Dio Cassius, care se referă la cetăţile dacice din Transilvania, dar cercetătorul rom&acirc;n consideră că această expresie se poate aplica şi la cetăţile din Moldova, cu excepţia celei de la Bărboşi. Configuraţia terenului pe care erau amplasate oferea acestor cetăţi o foarte bună apărare naturală. &Icirc;n general ele ocupă un promontoriu, fiind apărate din trei părţi de pante abrupte; cu toate acestea s-a dovedit că &icirc;ntreaga cetate sau numai părţile ei vulnerabile erau apărate de anumite elemente de fortificaţie. Apărarea naturală, dublată de una artificială, concepută şi realizată de m&acirc;na omului, sporea capacitatea defensivă a cetăţii, transform&acirc;nd-o &icirc;ntr-o fortăreaţă greu accesibilă.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Aşezarea getică de la Poiana &ndash; a fost loc de refugiu unde se putea adăposti populaţia &icirc;n vremuri de grea &icirc;ncercare</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Aceste &icirc;nălţimi fortificate din Moldova au fost locuri de refugiu unde se putea adăposti populaţia &icirc;n vremuri de grea &icirc;ncercare. Datorită funcţiei de loc de refugiu, aceste cetăţi au putut deveni cu timpul reşedinţele unor conducători, &icirc;n acest caz put&acirc;nd fi socotite drept centre militare, puncte de sprijin şi de apărare &icirc;n cazul unui război. Altele puteau deveni centre politice, unde se putea aşeza conducătorul mai multor triburi de la răsărit de Carpaţi.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Uneltele descoperite &icirc;n aceste cetăţi, urmele de metalurgie şi cuptoarele de ars ceramică, reprezintă dovezi concludente că aceste cetăţi erau şi mici centre meşteşugăreşti cu ateliere &icirc;n care activau meşteri locali.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Cetăţuia de la Poiana este localizată &icirc;n marginea de nord-vest a satului Poiana, judeţul Galaţi, pe un pinten de terasă din st&acirc;nga Siretului, mult &icirc;nălţată faţă de nivelul apei, desprins de aceasta printr-o viroagă naturală, unde, mai t&acirc;rziu, s-a amenajat un şanţ de apărare.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:35.4pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Poziţia aşezării oferă o vizibilitate bună spre Valea Siretului, &icirc;ntre Adjud şi Mărăşeşti, Valea Trotuşului, Măgura Odobeştilor şi Munţii Vrancei, reprezent&acirc;nd un punct strategic deosebit de important &icirc;n această zonă.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Iniţiativa cercetării acestei aşezări aparţine lui Spiru Haret</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Iniţiativa cercetării acestei aşezări aparţine lui Spiru Haret, care &icirc;n şedinţa Academiei Rom&acirc;ne din 18 septembrie 1892, atrage atenţia asupra staţiunii antice de la Poiana, pentru ca la 14 mai 1899 să revină asupra comunicării din 1892, dar Tocilescu &icirc;i răspunde că această staţiune se distruge mereu şi nu poate fi păzită.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n şedinţa din 3 februarie 1912 Haret &icirc;l roagă pe Vasile P&acirc;rvan să cerceteze această staţiune şi pentru ca să nu uite sau să am&acirc;ne, a doua zi &icirc;i trimite o scrisoare &icirc;n acelaşi sens.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n ședința Academiei Rom&acirc;ne din 20 septembrie 1913, Vasile P&acirc;rvan prezintă situația stațiunii antice de la Poiana, &icirc;n mare parte prăbușită &icirc;n r&acirc;u. Această comunicare este rezultatul mai multor sondaje arheologice efectuate de acesta &icirc;n așezarea civilă de la Poiana.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Totuși, primele cercetări arheologice preliminare le &icirc;ntreprinde Gh. Ștefan, membru al Școlii Rom&acirc;ne din Roma, rezultatele acestora fiind prezentate parțial de către P&acirc;rvan &icirc;n Getica. Din 1927 cercetarea arheologică a stațiunii de la Poiana este &icirc;ncredințată lui Radu și Ecaterina Dunăreanu Vulpe, de la Muzeul Național de Antichități din București. Misiunea acestora este aceea de a veni cu informații complete privind locuirea getică de aici precum și &icirc;nsemnătatea acesteia &icirc;n istoria veche a Moldovei.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;ncep&acirc;nd din acest an s-au efectuat sondaje, aproape anual, &icirc;n diferite zone ale promontoriului, &icirc;n special &icirc;n acele părți unde se produceau masive alunecări de teren, &icirc;n urma cărora a fost distrusă cea mai mare parte a stațiunii. Rezultatele lor nu au fost &icirc;ntotdeauna consemnate dec&acirc;t parțial, multe descoperiri au fost donate altor muzee, iar altele au dispărut &icirc;n diferite &icirc;mprejurări. Astfel, artefactele rezultate &icirc;n urma săpăturilor din 1939-1940, efectuate de Radu Vulpe și Anton Nițu, cu fondurile Universității din Iași, au fost depuse la Muzeul de Antichități din acest oraș, iar &icirc;n timpul războiului fiind refugiate &icirc;n altă localitate s-au pierdut &icirc;n cea mai mare parte. Numai o mică parte din aceste descoperiri se mai păstrează la Institutul de Arheologie și Muzeul de Istorie din Iași.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Săpăturile sunt reluate &icirc;n 1949, fiind conduse de către R. Vulpe și un colectiv format din cercetători de la București, Iași și Cluj. &Icirc;n perioada 1949-1951 bogatul material arheologic rezultat este depozitat &icirc;n condiții improprii la Muzeul Național de Antichități din București, răm&acirc;n&acirc;nd &icirc;n majoritatea sa, inedite. Abia după transferarea acestuia la Muzeul din Tecuci a &icirc;nceput să fie spălat și prelucrat, dar marcarea materialelor nu s-a mai putut face din lipsa unor &icirc;nsemnări, ambalajele din h&acirc;rtie &icirc;n care au fost &icirc;mpachetate fiind distruse complet.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Unele identificări s-au mai putut face numai pe baza desenelor din carnetele de șantier. Rapoartele publicate &icirc;n Studii și Cercetări de Istorie Veche cuprind puține din cele mai reprezentative descoperiri precum și prima descriere stratigrafică a așezării.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n ultimii ani de viață R. Vulpe hotărăște reluarea cercetării materialului din săpăturile vechi, c&acirc;țiva ani la r&acirc;nd, ajutat de muzeografii Mircea Nicu și Stela Țau a identificat, pe baza carnetelor de săpături, vasele &icirc;ntregi și mai ales obiectele care s-au descoperit &icirc;n diferite straturi sau complexe.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n perioada 1985-1990 s-a reușit cercetarea aproape &icirc;n &icirc;ntregime a așezării</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Din anul 1985, la săpături va participa și S. Teodor, de la Institutul de Arheologie din Iași &icirc;mpreună cu M. Nicu și S. Țau, campaniile fiind finanțate de Filiala din Iași a Academiei Rom&acirc;ne și Muzeul din Tecuci. &Icirc;n perioada 1985-1990 s-a reușit cercetarea aproape &icirc;n &icirc;ntregime a așezării, rezultatele obținute au adus o contribuție esențială la &icirc;ntocmirea monografiei.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>După &icirc;ncetarea din viață a lui R. Vulpe, la solicitarea Ec. Vulpe, S. Teodor &icirc;mpreună cu M. Nicu și S. Țau vor continua prelucrarea tuturor descoperirilor și vor redacta mult așteptata monografie.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Suprafaţa redusă a aşezării a dus la o locuire intensă; cetăţuia, pe baza descoperirilor deosebite &icirc;nregistrate aici, a fost identificată, &icirc;n anul 1931, cu antica Piroboridava, formaţiune preurbană menţionată de către geograful alexandrin Ptolemeu.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>El menţionează c&acirc;teva nume de aşezări dacice &ndash; Zargidava, Tamasidava şi Piroboridava &ndash; aşezate &icirc;n apropierea r&acirc;ului Hierasos, identificat cu r&acirc;ul Siret. Descoperirea aşezărilor de la Poiana, Brad şi Răcătău acordă autoritate textului ptolemaic dar, &icirc;n acelaşi timp, infirmă coordonatele sale geografice privitoare la poziţionarea lor. Cu toate acestea Geographia lui Ptolemeu răm&acirc;ne un important izvor care, coroborat cu descoperirile arheologice, ne permite să identificăm aşezările menţionate &icirc;n cuprinsul său.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Act militar din timpul &icirc;mpăratului Traian</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Un alt izvor care a ajutat la identificarea Poianei cu antica Piroboridava a fost Papirusul Hunt. Acesta conţine textul unui act militar din timpul &icirc;mpăratului Traian, fiind un raport anual, pridianum, privitor la &icirc;mpărţirea unei trupe auxiliare: cohors I Hispanorum veterana quingenaria (equitata), care a făcut parte din armata Moesiei Inferioare. Detaşamente din cadrul acestei cohorte au fost trimise pentru acţiuni &icirc;n nordul Dunării, precum şi pentru pază la Piroboridava şi Buridava.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Rolul praesidium-ului de la Piroboridava era acela de a supraveghea drumul dintre gurile Dunării şi Transilvania prin valea Siretului şi pasul Oituz, calea naturală a legăturilor lui Decebal cu răsăritul.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n anul 1927, Radu şi Ecaterina Vulpe, menţionează patru straturi arheologice ce includ aşezări succesive &icirc;ncep&acirc;nd din epoca bronzului şi p&acirc;nă &icirc;n secolul II p. Chr. Cetăţuia de la Poiana a fost fortificată natural, datorită pantelor abrupte care mărginesc circa două treimi din suprafaţa sa, dar şi artificial.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>La &icirc;nceputul secolului I a. Chr. staţiunea de pe Cetăţuie a fost prevăzută cu un sistem de apărare const&acirc;nd din şanţ şi val de păm&acirc;nt pe latura de est. &Icirc;n unele locuri au putut fi observate şi urme ale unor st&acirc;lpi de lemn, care proveneau de la o palisadă ce a &icirc;ntărit sistemul defensiv. Tot &icirc;n acelaşi timp a fost amenajat, prin ad&acirc;ncirea şi lărgirea unei r&acirc;pe din partea de nord-est şi sud a aşezării, un şanţ ad&acirc;nc de circa 6 m şi lat de 10 m.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Fortificarea aşezării s-a făcut cu scopul ca acest centru, cu importanţă deosebită, să fie apărat at&acirc;t de unii duşmani apropiaţi, c&acirc;t şi ameninţării venite din sud, c&acirc;nd expansiunea Imperiului Roman ajunsese deja la Dunăre. Aceste elemente defensive sunt asemănătoare cu acelea din aşezările contemporane de la Brad şi Răcătău sau de la C&acirc;ndeşti şi Fitioneşti, judeţul Vrancea care constituie şi cele mai apropiate analogii pentru structura sistemului de apărare de la Poiana.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Piroboridava, de c&acirc;te ori a fost populată, tot de at&acirc;tea ori a fost şi părăsită</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Prezenţa a cinci niveluri de locuire de la Poiana nu arată o continuitate de viaţă absolută, aşa cum s-a crezut. Totuşi, s-a putut observa că de c&acirc;te ori a fost populată, tot de at&acirc;tea ori a fost şi părăsită, din diferite motive. Perioadele de părăsire s-au putut identifica &icirc;ntre nivelurile I şi II, c&acirc;nd, pe o perioadă de două-trei secole nu s-a locuit pe cetăţuie; precum şi &icirc;ntre nivelul Basarabi şi mijlocul secolului V a. Chr. c&acirc;nd acest loc este părăsit. &Icirc;n profilul stratigrafic se pot observa numeroase distrugeri şi incendieri, după care, imediat, urmează noi nivelări şi amenajări, refaceri de vetre şi locuinţe, dovadă că locul a fost preferat pentru locuire, deoarece oferea multiple avantaje economice şi strategice.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Alături de alte aşezări &icirc;ntărite şi intens locuite, Poiana a fost considerată o dava, centru evoluat, cu un pronunţat caracter cvasiurban. Dovezile care ar conduce către localizarea aici şi a unui centru religios sau administrativ sunt insuficiente; totuşi, existenţa aici a unui emporiu comercial este din plin documentată. Poziţia sa este strategică, fiind amplasată &icirc;n apropierea celui mai direct drum spre nord şi vest, spre aşezările dacice din Transilvania. Aflat la intersecţia drumurilor naturale, negustorii puteau desfăşura o activitate care a impus centrul de la Poiana &icirc;n epocă, prin prosperitatea sa &icirc;n toate domeniile economice.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Pătrunderea produselor elenistice &icirc;n mediul autohton trebuie pusă &icirc;n str&acirc;nsă legătură cu stadiul de dezvoltare socio-economică şi politică a populaţiilor care au venit &icirc;n contact cu lumea elenistică. Rezultatele cercetărilor au arătat că primele contacte ale negustorilor greci au avut loc acolo unde nu doar mediul geografic era permisibil, ci poate mai degrabă unde nivelul de dezvoltare şi de &icirc;nţelegere a populaţiilor locale, cu care au venit &icirc;n contact, era favorabil.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;ntre secolele VI-IV a. Chr. se pun bazele unor relaţii permanente cu populaţiile aflate la distanţe mari faţă de centrele de producţie, aceasta reprezent&acirc;nd prima etapă &icirc;n cadrul relaţiilor comerciale dintre lumea greco-elenistică şi autohtonii de la nord de Dunăre. Se pune problema dacă existau relaţii directe de schimb sau indirecte, prin intermediul unor populaţii care separau lumea getică de cea grecească.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>V. P&acirc;rvan şi D. Tudor sunt de părere că pătrunderea mărfurilor greceşti &icirc;n lumea getică s-a făcut ca urmare a relaţiilor directe dintre negustorii greci, intraţi cu corăbiile pe cursul Dunării şi chiar a unora dintre principalele r&acirc;uri din Dacia, şi autohtoni.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Dunărea a constituit principala cale de comunicaţie</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Alţi cercetători sunt de părere că unele colonii ca Histria şi Callatis facilitau contactul cu geţii de la nord de Dunăre, contribuind la cunoaşterea de către negustorii greci a acestor zone şi atragerea lor &icirc;n activitatea economică, tot mai intensă pe măsura intereselor reciproce. După cum vedem, Dunărea a constituit principala cale de comunicaţie la care putem adăuga şi unele r&acirc;uri mari din Dacia: Prut, Siret, Argeş etc.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Un argument al posibilităţii de navigare pe r&acirc;ul Siret &icirc;l reprezintă resturile de peşti mari de Dunăre şi c&acirc;rligele de undiţă de dimensiuni mari descoperite la Poiana, ceea ce demonstrează că debitul de apă al Siretului era mai bogat atunci ca urmare, probabil, a unui climat mai umed. Un debit mai mare al apei şi o albie mai ad&acirc;ncă şi mai regulată, permiteau pătrunderea navelor de pe Dunăre pe Siret &icirc;n sus p&acirc;nă la gura Trotuşului.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n ceea ce priveşte aceste r&acirc;uri, ele erau navigabile doar &icirc;n anumite perioade ale anului şi doar pe anumite porţiuni din cursurile lor; văile lor reprezent&acirc;nd principala cale de acces, at&acirc;t pe apă c&acirc;t şi pe uscat, fapt demonstrat de numeroasele descoperiri pe văile acestor r&acirc;uri.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n cazul &icirc;n care schimburile comerciale se făceau direct nu putem spune cu exactitate p&acirc;nă unde ajungeau negustorii greci, probabil că nesiguranţa drumurilor din mediul autohton &icirc;i determinau pe aceştia să nu depăşească anumite limite. Presupunem că din momentul &icirc;n care schimburile comerciale devin regulate, s-au stabilit şi anumite puncte de contact unde se efectuau tranzacţiile.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Trebuie menţionat şi faptul că regiunile getice au reprezentat o sursă de aprovizionare pentru lumea greacă, aici găsind cereale, miere, produse animaliere deosebit de apreciate, &icirc;n schimbul cărora primeau renumitele vinuri din Thasos, Knidos, Rhodos, Cos etc., ulei de măsline, ceramică, obiecte de metal, podoabe, monede şi alte categorii de mărfuri.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Studierea importurilor greco-romane descoperite &icirc;n aşezările de pe Valea Siretului &icirc;ntre secolele IV a. Chr. &ndash; I p. Chr. a scos &icirc;n evidenţă faptul că &icirc;n acest areal au existat intense schimburi comerciale pentru perioada amintită, principalele produse importate fiind vinul, uleiul de măsline, răşinile, coloranţii, ceramica fină, opaiţele precum şi vase din sticlă şi bronz. De departe, cele mai numeroase descoperiri sunt acelea de amfore, ambalaje care erau folosite pentru transportul, păstrarea şi conservarea vinurilor, uleiului de măsline dar şi a răşinelor şi coloranţilor.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Descoperirile de monede, izolate sau tezaurizate, vin să ilustreze cele mai vechi legături comerciale cu lumea elenistică. Drahmele histriene descoperite la Poiana, &icirc;nlocuite treptat cu cele callatiene şi de la Filip al II-lea, indică unul dintre locurile unde se făceau schimburi pe bază de monedă, aşezarea de la Poiana, datorită poziţiei sale a fost unul din puţinele centre care, de timpuriu, a reprezentat locul de desfacere a mărfurilor greceşti dar şi de aprovizionare a locuitorilor din aşezările getice &icirc;nvecinate.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Cele aproximativ 230 amfore descoperite la Poiana, care provin din diferite insule din Marea Egee sau din centre de pe litoralul Mării Negre, datate &icirc;ntre secolele IV a. Chr. &ndash; I p. Chr., indică existenţa unei preocupări continui &icirc;n domeniul desfacerii de mărfuri.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Intensificarea şi permanentizarea schimburilor comerciale p&acirc;nă la pătrunderea influenţei romane a avut consecinţe importante pentru populaţia getică, probabil că au dus şi la o intensificare a producţiei de mărfuri cerute de aceştia. &Icirc;n ceea ce priveşte activitatea economică, cererea mare de cereale pentru export a dus la sporirea producţiei de gr&acirc;u de bună calitate, lucru posibil doar prin folosirea de unelte adecvate şi perfecţionate.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Mărfurile indică direcţiile spre care se orienta comerţul geţilor</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Multitudinea de amfore descoperite &icirc;n aşezările de pe Valea Siretului denotă un consum mare de vin şi ulei de măsline, ceea ce presupune existenţa unei clase sociale care &icirc;şi permitea achiziţionarea unor asemenea produse care veneau de la mari distanţe şi care nu aveau un preţ prea mic. Acest lucru ne poate arăta că &icirc;n aşezările unde numărul importurilor este copleşitor şi care sunt catalogate drept centre comerciale să fi existat o aristocraţie care să consume aceste produse. Mărfurile indică direcţiile spre care se orienta comerţul geţilor şi anume Marea Mediterană, Orient, oraşele pontice, nordul Italiei etc.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Odată cu intensificarea relaţiilor comerciale marile aşezări getice de pe Valea Siretului au evoluat devenind adevărate emporii unde se desfăceau produsele de import şi de unde acestea erau difuzate mai departe spre micile aşezări din jurul acestora. Unele dintre acestea se pare că au devenit centre specializate de desfacere a anumitor mărfuri, din care putem &icirc;nţelege că &icirc;n ele se desfăceau cu precădere anumite mărfuri şi nu doar o singură categorie.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Bogatul material de import descoperit &icirc;n marile davae de pe Siret atestă o viaţă economică cu un puls rapid de dezvoltare. Această evoluţie s-a datorat &icirc;n primul r&acirc;nd poziţiei strategice pe care o ocupau pe principala rută comercială de le Est de Carpaţi şi care era reprezentată de Valea Siretului.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>

                </div>
            </div>
        </div>
    </div>
    <hr>

    <?php require_once './footer.php';  ?>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/clean-blog.js"></script>
</body>

</html>