<?php
require_once './core/init.php';
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Situl Negrilesti - Muzeul Tecuci</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-1.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-grid.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-reboot.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap-utilities.compiled.css">
    <link rel="stylesheet" href="assets/css/bootstrap/bootstrap.compiled.css">
    <link rel="stylesheet" href="assets/scss/styles.css">
</head>

<body>
    <?php require_once 'navbar.php'; ?>
    <!-- <header class="masthead" style="background-image:url('assets/img/paleontologie.jpg');     background-attachment: fixed;
    background-position: bottom;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto position-relative">
                    <div class="site-heading">
                        <h1><strong>Paleontologie</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header> -->

    <header class="masthead" style="background-image:url('assets/img/negrilesti.jpg');background-position:bottom center;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto position-relative">
                    <div class="site-heading">
                        <h1>Muzeul de Istorie&nbsp;</h1>
                        <h1>Teodor Cincu</h1>
                        <span class="subheading">
                            Situl Negrilesti
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- <h3 style="color: #0085a1;text-align: center;font-family: 'Lora',serif;">SCURT ISTORIC</h3> -->
    <h2 style="text-align: center;font-family: 'Poppins',sans-serif;"><br><strong>Colecții ale muzeului - Situl arheologic Negrilesti</strong><br><br></h2>
    <div class="container" style="text-align: center;">
        <div class="text_istoric">
            <div class="istoric_text_column istoric_content_element ">
                <div class="text_istoric">
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Scurt istoric al așezării</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Satul Negrileşti este un vechi sat medieval, toponimul Negrileşti se folosea la 13 martie 1528 c&acirc;nd este amintit &bdquo;satul de pe B&acirc;rlad, unde au fost jude Buda şi Drăgoiu, am&acirc;ndouă judeciile, care acum se numesc Negrileşti&rdquo;.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&Icirc;n secolul al XVIII- lea este amintită &bdquo;Biserica lui Frangolea&rdquo; construită &icirc;nainte de 1752, iar &icirc;n 1854 boierul Iancu Giurgea construieşte actuala biserică, cu hramul &bdquo;Sf&acirc;ntul Nicolae&rdquo;, aflată l&acirc;ngă actuala şcoală, chiar &icirc;n situl arheologic.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Fragmente ceramice de factură medievală au fost descoperite &icirc;n diverse puncte de pe teritoriul satului, chiar şi &icirc;n situl Şcoala Generală, unele dintre acestea afl&acirc;ndu-se &icirc;n colecţia muzeului din Tecuci.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Scurtă prezentare a sitului</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Situl a fost semnalat &icirc;n anul 1981 de către locuitorul Ghiţă Chiscop care s-a prezentat la Muzeul Mixt Tecuci cu c&acirc;teva vase aparţin&acirc;nd culturii S&acirc;ntana de Mureş, descoperite de t&acirc;nărul Toader Bolohan, &icirc;n profilul abrupt al malului st&acirc;ng al r&acirc;ului B&acirc;rlad. &Icirc;n urma efectuării unei săpături de salvare a fost constatată existenţa unui cuptor de producere a ceramicii, distrus, aparţin&acirc;nd secolului al IV-lea p. Hr. precum şi a numeroase fragmente ceramice aparţin&acirc;nd culturilor Starčevo-Criş, Noua, S&acirc;ntana de Mureş-Cerneahov, Dridu şi din secolul al XIX-lea, acestea fiind răsp&acirc;ndite pe o suprafaţă de aproximativ 10.000 mp.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Situl arheologic Negrileşti este inclus &icirc;n Lista Monumentelor Istorice din anul 2004, la poziţia 57, cod Gl-I-s-B-02988 şi se află situat &icirc;n curtea şcolii gimnaziale din sat.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Aflat pe o terasa joasă a r&acirc;ului B&acirc;rlad, satul a avut de suferit &icirc;n urma fenomenului de eroziune a malurilor, multe terenuri fiind distruse. &Icirc;n dreptul sitului arheologic albia a avansat spre est cu circa cinci metri din anul 1981 p&acirc;nă &icirc;n prezent, distrug&acirc;nd o bună parte din sit.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Punctul &bdquo;Zaharia&rdquo; face parte integrantă din situl arheologic de la Negrileşti şi este &icirc;n zona de maxim pericol de distrugere datorită acţiunii apei r&acirc;ului B&acirc;rlad.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Dat fiind pericolul la care este supus situl arheologic &icirc;n acest punct, cercetarea din anul 2007 a avut rolul de a salva materialul arheologic existent şi de a consemna complexele arheologice din acest perimetru.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n anul 2007 săteanul Toader Bolohan a semnalat Primăriei Negrileşti apariţia unor vase ceramice mari, &icirc;n ruptura produsă de r&acirc;ul B&acirc;rlad, &icirc;n malul st&acirc;ng, din dreptul proprietăţii consătenei Zaharia Vasilica. &Icirc;n urma deplasării la faţa locului şi la solicitarea Primăriei Negrileşti, s-a decis realizarea unei cercetări preventive &icirc;n acest punct şi a unei evaluări a potenţialului arheologic al zonei.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n urma cercetării arheologice preventive au fost puse &icirc;n evidenţă numeroase urme materiale ce confirmă bogăţia acestui sit.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;ncep&acirc;nd cu anul 2007 și p&acirc;nă &icirc;n prezent Muzeul de Istorie &bdquo;Paul Păltănea&rdquo;, Galați, &icirc;n colaborare cu Muzeul de Istorie &bdquo;Teodor Cincu&rdquo;, Tecuci, a realizat, anual, campanii de cercetare arheologică &icirc;n acest sit, &icirc;n diverse puncte din suprafața de aproximativ 12 ha, c&acirc;t &icirc;nsumează situl arheologic Negrilești &bdquo;Curtea Școlii&rdquo;.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n anul 2007 au fost cercetate trei unitati de săpătură, &icirc;nsum&acirc;nd 30m2, &icirc;n punctele Zaharia si La Izvor. &Icirc;n sectiunea S1 si caseta Cas.1, au fost descoperite urme materiale din epoca bronzului și din secolele IV-V d. Hr., const&acirc;nd &icirc;n fragmente ceramice, oase de animale, urme de vatră și de locuință, gropi menajere. La circa 30 m spre sud, &icirc;n apropierea curții școlii, la punctul Izvor, a fost practicată caseta Cas.2/2007 de unde au fost recoltate fragmente ceramice neolitice (cultura Starcevo-Criș). La nord si sud de punctul Zaharia, &icirc;n ruptura malului, au fost observate urme de locuire, gropi menajere cu material arheologic din diferite perioade istorice. Dintr-o astfel de groapă, aflată la 2 m sud de caseta Cas.1, au fost recuperate fragmente ceramice ce provin de la patru vase de mari dimensiuni și de la două amfore, datate &icirc;n secolele IV-V p. Chr.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&Icirc;n anul 2008 au fost trasate patru unități de cercetare, trei secțiuni și o casetă. &Icirc;n secțiunile S3, S4, S5 precum si &icirc;n caseta Cas.3/2008, au fost descoperite urme materiale datate &icirc;n epoca bronzului, secolul IV p. Chr., secolele VIII-X si secolul al XIX-lea. Au fost puse &icirc;n evidență diferite structuri arheologice, gropi menajere, vatră, locuințe din secolul IV, conducta de aducțiune a apei datată &icirc;n secolul al XIX-lea și au fost prelevate materiale ceramice, osteologice si din metal.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Cercetarea arheologică sistematică din anul 2009 a constat &icirc;n săparea a trei secțiuni S2, S6 si S7, cu o suprafata totala de 80 m2, &icirc;n punctele Curtea Scolii și La Punte. Au fost golite 11 gropi menajere cu material arheologic specific culturilor Criș, Noua, S&acirc;ntana de Mureș-Cernjachov.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Tot &icirc;n anul 2009 a &icirc;nceput cercetarea preventivă &icirc;n punctul Centrala Termică, continuată și &icirc;n anul 2010. Au fost cercetați 100 m2 &icirc;n cele cinci secțiuni, notate Sc1, Sc2, Sc3, Sc4 si Sc5. &Icirc;n acest perimetru a fost surprinsă o mare densitate de complexe arheologice din epoca bronzului, secolul IV p. Chr. și secolele VIII-X p. Chr. Au fost descoperite 14 gropi, 3 locuințe, un cuptor pentru ceramică și o vatră.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &Icirc;n campania anului 2011, &icirc;n sectorul Curtea Școlii, a fost trasată o secțiune magistrala, SM1 (70m/2m), orientată E-V, și două casete (Cas.1-2; Cas.2). Cercetarea acestor unități de săpătură a permis punerea &icirc;n evidență a trei locuințe specifice culturii S&acirc;ntana de Mures-Cernjachov, a două complexe de locuire din epoca modernă, a 25 de gropi datate &icirc;n epoca bronzului si cea post-romană (secolul IV p. Chr.), a unei vetre, precum și a unor resturi materiale din perioada secolelor XVIII-XIX (beci, conductă de aducțiune a apei, ceramică, metal, sticlă).</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Cercetarea efectuata &icirc;n 2012 a dus la deschiderea a 15 suprafețe de săpătură, 12 secțiuni și trei casete, amplasate &icirc;n trei sectoare diferite. Mentionăm ca situl a fost &icirc;mparțit &icirc;n 64 de carouri, de 50m/50m, conform cu ridicarea topo, pentru a ușoară localizarea unităților de săpătură și a evita denumirile locale ce pot suferi modificări de-a lungul timpului.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Muzeul de Istorie &bdquo;Teodor Cincu&rdquo; a realizat, &icirc;n cei 14 ani de c&acirc;nd se desfășoară cercetări arheologice preventive &icirc;n sit, un număr de doar 15 unități de săpătură (secțiuni și casete de dimensiuni variabile) din care au rezultate un număr foarte mare de fragmente ceramice, vase &icirc;ntregibile, unelte și arme din os și piatră, importante pentru studiul comunităților umane care au trăit &icirc;n această zonă &icirc;n perioada mileniului VI a. Chr &ndash; sec. XIX.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Patrimoniul muzeului, &icirc;n urma cercetărilor arheologice efectuate &icirc;n acest sit, s-a &icirc;mbogățit cu un număr de 157 piese (vase ceramice, unelte, arme din piatră și os etc).</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Cercetările arheologice reluate după mai bine de 3 ani &icirc;n anul 2021</span></strong></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Cercetările arheologice reluate după 3 ani de muzeului tecucean</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Muzeul de Istorie &bdquo;Teodor Cincu&rdquo; Tecuci &icirc;n colaborare cu Muzeul de Istorie &bdquo;Paul Păltănea&rdquo; Galați a reluat anul acesta cercetările sistematice &icirc;n situl arheologic de la Negrilești.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Situl a fost semnalat &icirc;n anul 1981. &Icirc;n urma efectuării unei săpături de salvare a fost constatată existenţa unui cuptor de producere a ceramicii, distrus, precum şi a numeroase fragmente ceramice aparţin&acirc;nd culturilor Starčevo-Criş, Noua, S&acirc;ntana de Mureş-Cerneahov, Dridu şi din secolul al XIX-lea, acestea fiind răsp&acirc;ndite pe o suprafaţă de aproximativ 10.000 mp.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Situl arheologic Negrileşti este inclus &icirc;n Lista Monumentelor Istorice din anul 2004, la poziţia 57, cod Gl-I-s-B-02988 şi se află situat &icirc;n curtea şcolii gimnaziale din sat.&nbsp;</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Muzeul de Istorie &bdquo;Teodor Cincu&rdquo; Tecuci a realizat, &icirc;n cei 14 ani de c&acirc;nd se desfășoară cercetări arheologice preventive &icirc;n sit, un număr de 15 unități de săpătură (secțiuni și casete de dimensiuni variabile) din care au rezultate un număr foarte mare de fragmente ceramice, vase &icirc;ntregibile, unelte și arme din os și piatră, importante pentru studiul comunităților umane care au trăit &icirc;n această zonă &icirc;n perioada mileniului VI a. Chr. &ndash; sec. XIX.</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Patrimoniul muzeului tecucean, &icirc;n urma cercetărilor arheologice efectuate &icirc;n acest sit, s-a &icirc;mbogățit cu un număr de 157 piese (vase ceramice, unelte, arme din piatră și os etc.).</span></p>
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:35.4pt;'><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Mulțumim partenerilor noștri - Muzeului de Istorie &bdquo;Paul Păltănea&rdquo; Galați pentru colaborare, c&acirc;t și Primăriei și Consiliului Local Tecuci pentru suportul financiar acordat &icirc;n vederea inițierii cercetărilor &icirc;n anul 2021.</span></p>

                </div>
            </div>
        </div>
    </div>
    <hr>

    <?php require_once './footer.php';  ?>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/clean-blog.js"></script>
</body>

</html>